{{- if .Values.required }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gatekeeper
  namespace: openshift-operators
spec:
  channel: stable
  name: gatekeeper-operator-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
