{{- if .Values.required }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gatekeeper-operator-sub
  namespace: openshift-gatekeeper-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: stable
  name: gatekeeper-operator
  source: gatekeeper-operator
  sourceNamespace: openshift-gatekeeper-operator
{{- end }}
