{{- if .Values.required }}
{{- if .Values.htpasswd }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.htpasswdSecretName }} 
data:
  htpasswd: {{ .Files.Get "files/htpasswd" | b64enc }}
{{- end }}
{{- end }}
