{{- if .Values.required }}
{{- if .Values.htpasswd }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.htpasswdSecretName }}
  namespace: openshift-config
type: Opaque 
data:
  htpasswd: {{ .Files.Get "files/htpasswd" | b64enc | quote }}
{{- end }}
{{- end }}
