{{- if .Values.required }}
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  {{- if .Values.htpasswd }}
  - name: htpasswd 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: {{ .Values.htpasswdSecretName }}
   {{- end }}
{{- end }}
