{{- if .Values.required }}
apiVersion: batch/v1
kind: Job
metadata:
  name: label-workers-large-pods
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: openshift-gitops-argocd-application-controller
      containers:
      - name: label-workers-large-pods
        image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        args:
        - |
          oc label --overwrite machineconfigpool worker custom-kubelet=large-pods
      restartPolicy: OnFailure
{{- end }}
